import { describe, expect, it } from 'vitest'
import { Selector } from '../select'
import { sortBy } from 'lodash-es'

describe('Selector', () => {
  it('should be select', () => {
    const selector = new Selector(['a', 'b', 'c', 'd', 'e'])
    selector.click('a')
    expect(selector.selected).toEqual(['a'])
    selector.click('b')
    selector.click('a')
    expect(selector.selected).toEqual(['b'])
  })
  it('should be range select', () => {
    const selector = new Selector(['a', 'b', 'c', 'd', 'e'])
    selector.click('a')
    selector.shiftDown()
    selector.click('c')
    expect(selector.selected).toEqual(['a', 'b', 'c'])
    selector.click('e')
    expect(selector.selected).toEqual(['a', 'b', 'c', 'd', 'e'])
    selector.click('c')
    expect(selector.selected).toEqual(['a', 'b', 'c'])
    selector.shiftUp()
    selector.click('e')
    expect(selector.selected).toEqual(['a', 'b', 'c', 'e'])
  })
  it('should be reverse select', () => {
    const selector = new Selector(['a', 'b', 'c', 'd', 'e'])
    selector.click('c')
    selector.shiftDown()
    selector.click('e')
    expect(selector.selected).toEqual(['c', 'd', 'e'])
    selector.click('a')
    expect(sortBy(selector.selected)).toEqual(['a', 'b', 'c'])
    selector.shiftUp()
    expect(sortBy(selector.selected)).toEqual(['a', 'b', 'c'])
  })
  it('should be remove mode', () => {
    const selector = new Selector(['a', 'b', 'c', 'd', 'e'])
    selector.click('a')
    selector.shiftDown()
    selector.click('c')
    expect(selector.selected).toEqual(['a', 'b', 'c'])
    selector.shiftUp()
    selector.shiftDown()
    selector.click('c')
    expect(selector.selected).toEqual(['a', 'b'])
    selector.click('b')
    expect(selector.selected).toEqual(['a'])
    selector.click('d')
    expect(selector.selected).toEqual(['a', 'b'])
    selector.shiftUp()
    expect(selector.selected).toEqual(['a', 'b'])
  })
  it('should be cross select', () => {
    const selector = new Selector(['a', 'b', 'c', 'd', 'e'])
    selector.click('a')
    selector.shiftDown()
    selector.click('c')
    expect(selector.selected).toEqual(['a', 'b', 'c'])
    selector.shiftUp()
    selector.click('e')
    expect(selector.selected).toEqual(['a', 'b', 'c', 'e'])
    selector.shiftDown()
    selector.click('b')
    expect(sortBy(selector.selected)).toEqual(['a', 'b', 'c', 'd', 'e'])
    selector.shiftUp()
    expect(sortBy(selector.selected)).toEqual(['a', 'b', 'c', 'd', 'e'])
  })
  it('should be set keys', () => {
    const selector = new Selector(['a', 'b', 'c', 'd', 'e'])
    selector.click('a')
    selector.shiftDown()
    selector.click('c')
    expect(selector.selected).toEqual(['a', 'b', 'c'])
    selector.setKeys(['a', 'b', 'c', 'd', 'e'])
    selector.click('e')
    expect(selector.selected).toEqual(['a', 'b', 'c', 'd', 'e'])
    selector.click('a')
    expect(selector.selected).toEqual(['a'])
    selector.setKeys(['h', 'i', 'j', 'k', 'l'])
    expect(selector.selected).toEqual([])
    selector.click('h')
    expect(selector.selected).toEqual(['h'])
    selector.click('j')
    expect(selector.selected).toEqual(['h', 'j'])
    selector.shiftUp()
    selector.click('i')
    selector.shiftDown()
    selector.click('k')
    expect(sortBy(selector.selected)).toEqual(['h', 'i', 'j', 'k'])
    selector.shiftUp()
    expect(sortBy(selector.selected)).toEqual(['h', 'i', 'j', 'k'])
  })
  it('async set keys', async () => {
    const selector = new Selector([])
    selector.setKeys(['a', 'b', 'c', 'd', 'e'])
    selector.click('a')
    expect(selector.selected).toEqual(['a'])
  })
  it('should be select all', () => {
    const selector = new Selector(['a', 'b', 'c', 'd', 'e'])
    selector.selectAll()
    expect(selector.selected).toEqual(['a', 'b', 'c', 'd', 'e'])
    selector.click('a')
    expect(selector.selected).toEqual(['b', 'c', 'd', 'e'])
    selector.selectAll()
    expect(selector.selected).toEqual(['a', 'b', 'c', 'd', 'e'])
    selector.selectAll()
    expect(selector.selected).toEqual([])
  })
  it('should be auto update selected in all selected', () => {
    const selector = new Selector(['a', 'b', 'c', 'd', 'e'])
    selector.selectAll()
    expect(selector.selected).toEqual(['a', 'b', 'c', 'd', 'e'])
    selector.setKeys(['a', 'b', 'c', 'd', 'e', 'f'])
    expect(selector.selected).toEqual(['a', 'b', 'c', 'd', 'e', 'f'])
  })
})
