import { LabelValue } from '$lib/components/custom/select/types'

export const languages: LabelValue[] = [
  { label: 'العربية - Arabic', value: 'ar' },
  { label: 'বাংলা - Bengali', value: 'bn' },
  { label: '简体中文 - Simplified Chinese', value: 'zh' },
  { label: 'Čeština - Czech', value: 'cs' },
  { label: 'Dansk - Danish', value: 'da' },
  { label: 'Nederlands - Dutch', value: 'nl' },
  { label: 'English - English', value: 'en' },
  { label: 'Suomi - Finnish', value: 'fi' },
  { label: 'Français - French', value: 'fr' },
  { label: 'Deutsch - German', value: 'de' },
  { label: 'Ελληνικά - Greek', value: 'el' },
  { label: 'עברית - Hebrew', value: 'he' },
  { label: 'हिन्दी - Hindi', value: 'hi' },
  { label: 'Magyar - Hungarian', value: 'hu' },
  { label: 'Bahasa Indonesia - Indonesian', value: 'id' },
  { label: 'Italiano - Italian', value: 'it' },
  { label: '日本語 - Japanese', value: 'ja' },
  { label: '한국어 - Korean', value: 'ko' },
  { label: 'Bahasa Melayu - Malay', value: 'ms' },
  { label: 'Norsk - Norwegian', value: 'no' },
  { label: 'فارسی - Persian', value: 'fa' },
  { label: 'Polski - Polish', value: 'pl' },
  { label: 'Português - Portuguese', value: 'pt' },
  { label: 'Română - Romanian', value: 'ro' },
  { label: 'Русский - Russian', value: 'ru' },
  { label: 'Español - Spanish', value: 'es' },
  { label: 'Kiswahili - Swahili', value: 'sw' },
  { label: 'Svenska - Swedish', value: 'sv' },
  { label: 'ไทย - Thai', value: 'th' },
  { label: 'Türkçe - Turkish', value: 'tr' },
  { label: 'Українська - Ukrainian', value: 'uk' },
  { label: 'اردو - Urdu', value: 'ur' },
  { label: 'Tiếng Việt - Vietnamese', value: 'vi' },
]
